"""Assemble GLSL sources from a prelude generated by the Python schema.

The anchor codebook and channel layout exist in exactly one place,
:mod:`chorusface.runtime.bds`. This module emits them as GLSL constants and injects
them into each stage, so the CPU and GPU views of a cell cannot drift.

The avatar runs a constraint-only tick: identity must never advect, so the
physics and semantic passes of the wider field substrate are deliberately
absent here.
"""

from __future__ import annotations

from importlib.resources import files
from typing import Final

from chorusface.runtime.bds import (
    ANCHORS,
    HUMAN_LOCK_CHANNEL,
    PRIORITY_CHANNEL,
    PRIORITY_LEVELS,
    VECTOR_DIMENSIONS,
    VELOCITY_CHANNELS,
)

PRELUDE_TOKEN: Final = "//#prelude"
MAX_COMMANDS_PER_TICK: Final = 256
COMMAND_FLOATS: Final = 8
WORKGROUP_SIZE: Final = 16
CLAMP_LIMIT: Final = 1.5
SNAP_THRESHOLD: Final = 1.5
EMPTY_EPSILON: Final = 0.01
#: Per-tick survival of tissue velocity. The avatar ships no physics pass, so
#: this is the only thing that dissipates speech energy; at 60 Hz it gives the
#: impulse field a ~0.13 s tail instead of ratcheting up to ``CLAMP_LIMIT``.
VELOCITY_DAMPING: Final = 0.88
#: Unlocked soft cells exchange velocity with Moore neighbors (ch 0/1 only).
#: This is NOT material advection — albedo / lock / density stay put.
VELOCITY_NEIGHBOR_BLEND: Final = 0.08

COMPUTE_PASSES: Final[tuple[str, ...]] = ("constraint",)


def anchor_names() -> list[str]:
    return list(ANCHORS)


def priority_scale() -> float:
    """Normalization factor mapping a priority level onto ``[0, 1]``."""
    return 1.0 / float(max(PRIORITY_LEVELS.values()))


def normalize_priority(level: int) -> float:
    if level not in PRIORITY_LEVELS.values():
        raise ValueError(f"Unknown priority level: {level}")
    return level * priority_scale()


def generate_prelude() -> str:
    """Return the GLSL constants shared by every stage."""
    rows = ",\n".join(
        "    float[%d](%s)"
        % (
            VECTOR_DIMENSIONS,
            ", ".join(_format_float(value) for value in vector),
        )
        for vector in ANCHORS.values()
    )
    names = "".join(
        f"// anchor {index} = {name}\n" for index, name in enumerate(ANCHORS)
    )
    return f"""// Generated from chorusface/runtime/bds.py; do not edit by hand.
const int CHANNELS = {VECTOR_DIMENSIONS};
const int ANCHOR_COUNT = {len(ANCHORS)};
const int PRIORITY_CHANNEL = {PRIORITY_CHANNEL};
const int HUMAN_LOCK_CHANNEL = {HUMAN_LOCK_CHANNEL};
const int MAX_COMMANDS = {MAX_COMMANDS_PER_TICK};
const int VELOCITY_CHANNELS = {len(VELOCITY_CHANNELS)};
const float CLAMP_LIMIT = {_format_float(CLAMP_LIMIT)};
const float SNAP_THRESHOLD = {_format_float(SNAP_THRESHOLD)};
const float EMPTY_EPSILON = {_format_float(EMPTY_EPSILON)};
const float VELOCITY_DAMPING = {_format_float(VELOCITY_DAMPING)};
const float VELOCITY_NEIGHBOR_BLEND = {_format_float(VELOCITY_NEIGHBOR_BLEND)};

{names}const float ANCHOR_TABLE[ANCHOR_COUNT][CHANNELS] = float[ANCHOR_COUNT][CHANNELS](
{rows}
);

struct Cell {{
    float value[CHANNELS];
}};

struct PaintCommand {{
    vec4 segment;
    vec4 settings;
}};

float anchor_value(int anchor, int channel) {{
    return ANCHOR_TABLE[clamp(anchor, 0, ANCHOR_COUNT - 1)][channel];
}}

float group_norm(float state[CHANNELS], int group) {{
    float total = 0.0;
    int first = group * 8;
    for (int offset = 0; offset < 8; ++offset) {{
        float component = state[first + offset];
        total += component * component;
    }}
    return sqrt(total);
}}

float distance_to_segment(vec2 point, vec2 start, vec2 end) {{
    vec2 span = end - start;
    float length_squared = dot(span, span);
    if (length_squared < 1e-6) {{
        return length(point - start);
    }}
    float position = clamp(dot(point - start, span) / length_squared, 0.0, 1.0);
    return length(point - (start + position * span));
}}

bool is_locked(float state[CHANNELS]) {{
    return state[HUMAN_LOCK_CHANNEL] >= 0.5;
}}
"""


def shader_source(name: str) -> str:
    """Read a packaged shader stage verbatim."""
    return files("chorusface").joinpath("shaders", name).read_text(encoding="utf-8")


def load_shader(name: str) -> str:
    """Read a shader stage and expand its prelude token."""
    source = shader_source(name)
    if PRELUDE_TOKEN not in source:
        raise ValueError(f"{name} does not contain the {PRELUDE_TOKEN} token")
    return source.replace(PRELUDE_TOKEN, generate_prelude())


def load_compute_passes() -> dict[str, str]:
    """Return the assembled source for each compute stage, in execution order."""
    return {name: load_shader(f"{name}.comp") for name in COMPUTE_PASSES}


def load_tick_ingest_shader() -> str:
    """TickFeed full-face KEY/DELTA ingest (not in COMPUTE_PASSES ping-pong)."""
    return load_shader("tick_ingest.comp")


def _format_float(value: float) -> str:
    text = repr(float(value))
    return text if ("." in text or "e" in text or "E" in text) else f"{text}.0"


__all__ = [
    "CLAMP_LIMIT",
    "COMMAND_FLOATS",
    "COMPUTE_PASSES",
    "EMPTY_EPSILON",
    "MAX_COMMANDS_PER_TICK",
    "PRELUDE_TOKEN",
    "SNAP_THRESHOLD",
    "VELOCITY_DAMPING",
    "WORKGROUP_SIZE",
    "anchor_names",
    "generate_prelude",
    "load_compute_passes",
    "load_shader",
    "load_tick_ingest_shader",
    "normalize_priority",
    "priority_scale",
    "shader_source",
]
